-- 1. Create a table for individual files
create table file_locks (
  id bigint generated by default as identity primary key,
  filename text unique not null,
  is_locked boolean default false,
  last_accessed timestamp with time zone
);

-- 2. Enable Realtime (So the UI updates instantly)
alter publication supabase_realtime add table file_locks;

-- 3. Security Policies (Allow R/W)
alter table file_locks enable row level security;

create policy "Allow all access"
on file_locks for all
using (true)
with check (true);
